function(print_configuration_summary)
  message(STATUS "")
  message(STATUS "******** Summary ********")
  message(STATUS "General:")
  message(STATUS "  System                : ${CMAKE_SYSTEM_NAME}")
  message(STATUS "  C++ compiler          : ${CMAKE_CXX_COMPILER}")
  message(STATUS "  C++ compiler version  : ${CMAKE_CXX_COMPILER_VERSION}")
  string(STRIP "${CMAKE_CXX_FLAGS}" CMAKE_CXX_FLAGS_STRIP)
  message(STATUS "  CXX flags             : ${CMAKE_CXX_FLAGS_STRIP}")
  message(STATUS "  Build type            : ${CMAKE_BUILD_TYPE}")
  message(STATUS "  Install prefix        : ${CMAKE_INSTALL_PREFIX}")
  if(NOT USE_HIP_CPU)
    message(STATUS "  Device targets        : ${GPU_TARGETS}")
  endif()
  message(STATUS "")
  message(STATUS "  BUILD_TEST                : ${BUILD_TEST}")
  message(STATUS "  BUILD_BENCHMARK           : ${BUILD_BENCHMARK}")
  message(STATUS "  BUILD_EXAMPLE             : ${BUILD_EXAMPLE}")
  message(STATUS "  USE_HIP_CPU               : ${USE_HIP_CPU}")
endfunction()
